### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by wtachau** [rossfoley/darts#7]

**Comment by rossfoley** [comment]
Based on the discussion, it looks like possibilities to rank people are: win percentage, total wins, or average score

**Comment by wtachau** [comment]
i'd be interested to see the win margin develop as a metric, then perhaps "average margin" could be used.

(margin would normalize games like 78-75 and 423-420)

**Comment by rossfoley** [comment]
In the case of a game like 78-75, would the win margin be 4%?

**Comment by wtachau** [comment]
up for debate, but I was thinking absolute margin, i.e. 3 points

**Comment by rossfoley** [comment]
Done
